src/command/global/dist.ts
src/command/global/factories.ts
src/command/global/mines.ts
src/command/global/nuke.ts
src/command/global/prox.ts
src/command/global/region.ts
src/command/global/remind.ts
src/command/global/reminder.ts
src/command/global/rigs.ts
src/command/global/totals.ts
src/index.ts

slash command stubs

---

.gitignore
package.json
src/decorators.ts
src/error.ts
src/handler/global/dist.ts
src/index.ts
src/logger.ts
yarn.lock

- catch errors in event handlers
- added `BotError` class that notify the user if thrown if a command or button handler
- added Winston for logging

Error handling

---

package.json
src/handler/guild/channel.ts
yarn.lock

added /channel command

---

src/handler/global/dis.ts
src/handler/global/nuke.ts
src/map/geometry.ts
src/map/util.ts

implemented /dis and /nuke

---

src/entity/LandAndFacilities.ts
src/handler/global/spawns.ts
src/handler/job/monitorUsers.ts
src/handler/job/monitorWorld.ts
src/repository/LandAndFacilitiesRepository.ts

Add spawn command and improve world monitoring

---

package.json
src/bot.ts
src/config.ts
src/decorators/AfterCommandUpdate.ts
src/entity/Country.ts
src/handler/guild/role.ts
src/handler/guild/verifyAll.ts
src/index.ts
src/logger.ts
src/repository/CommandRepository.ts
src/scripts/updateCommands.ts
src/scripts/updateStaticData.ts
yarn.lock

resolves #45 
- added the `Country` schema to store static information such as country names, coordinates and regions
- added `yargs` for better option parsing
- cleaned up the bot bootstrapping code, and split command updates into a separate script
- added `update_resources` command to update the country data
(The schema isn't actually used by anything yet)

Country metadata schema

---

src/bot.ts
src/handler/global/spawns.ts
src/repository/LandAndFacilitiesRepository.ts
src/scripts/updateCommands.ts

read country names from db

---

.gitignore
src/bot.ts
src/handler/global/dis.ts
src/handler/global/nuke.ts
src/handler/util/countryComplete.ts
src/map/index.ts
src/map/kdtree.ts
src/scripts/updateStaticData.ts
src/util/assert.ts

- refactored interface to access map related metadata
- generates map derived data structures during `update_resources` and stores them in json files

refactored map data storage and write derived data to fs

---

src/entity/LandAndFacilities.ts
src/handler/global/spawns.ts
src/repository/LandAndFacilitiesRepository.ts
src/service/facilitiesChanges.ts

- add columns for GDs and ADs
- update spawn and control col names to no longer be misleading

Update land and facilties entity

---

src/handler/global/prox.ts
src/map/kdtree.ts
src/map/util.ts
src/repository/UnitChangeRepository.ts

implemented /prox

---

src/handler/global/factories.ts
src/handler/global/mines.ts
src/handler/global/rigs.ts
src/repository/LandAndFacilitiesRepository.ts
src/service/mapCommands.ts

implements /factories, /mines and /rigs
resolves #31

Income commands

---

src/handler/global/factories.ts
src/handler/global/mines.ts
src/handler/global/rigs.ts
src/service/mapCommands.ts
src/service/util/constants.ts

- lowered threshold for income commands to 1% of the total amount
- created `FacilityIncome` enum

lowered threshold for income commands and added constants

---

.github/workflows/node.js.yml

Workflow cache

---

src/handler/guild/verify.ts
src/handler/guild/verifyAll.ts
src/handler/job/monitorRanks.ts
src/service/nickname.ts
src/service/verifyService.ts

also users will be auto verified upon joining the server

Fix verification and rank nicknames being separate and overwriting each other

---

src/handler/global/prox.ts
src/map/kdtree.ts
src/repository/UnitChangeRepository.ts

Fixes bugs with /prox resolves #89, #109 and #110

---

src/decorators/CommandHandler.ts
src/handler/global/dis.ts
src/handler/global/factories.ts
src/handler/global/mines.ts
src/handler/global/nuke.ts
src/handler/global/personalstats.ts
src/handler/global/prox.ts
src/handler/global/region.ts
src/handler/global/rigs.ts
src/handler/global/spawns.ts
src/handler/global/totals.ts
src/handler/guild/channel.ts
src/handler/guild/role.ts
src/repository/LandAndFacilitiesRepository.ts

add default values for map queries

---

package.json
src/bot.ts
src/handler/global/spawns.ts
yarn.lock

also moves the numbers into embed fields and slightly changes the format

added totals to /spawns

---

src/handler/guild/verifyAll.ts
src/service/nickname.ts

using wrong UserRank object so id is null when adding a brand new user

Fix bug with verify-all

---

src/handler/guild/verify.ts
src/handler/guild/verifyAll.ts
src/handler/job/monitorRanks.ts
src/service/nicknameService.ts
src/service/util/team.ts
src/service/verifyService.ts

But will still update nickname as normal
...probably. i didnt test it 👀

No team role/rank if round over

---

src/handler/guild/verify.ts
src/handler/guild/verifyAll.ts
src/repository/UserRankRepository.ts
src/service/nicknameService.ts
src/service/verifyService.ts

hopefully fixes the excessive amount of discord api requests

combined nickname and role updates

---

README.md
docker/collector-config.yml
docker/docker-compose.yml
package.json
src/bot.ts
src/datasource.ts
src/decorators/ScheduledJob.ts
src/decorators/index.ts
src/djsInstrumentation.ts
src/handler/job/monitorRanks.ts
src/handler/job/monitorReminders.ts
src/handler/job/monitorUsers.ts
src/handler/job/monitorWorld.ts
src/index.ts
src/parser.ts
src/tracing.ts
tsconfig.json
yarn.lock

enables OTEL tracing when the new `--tracing` flag is set

added OTEL tracing
